language: ruby
script: bundle exec jekyll build
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: Hab4cUe3EPrkkIfbie+5o1opxMZSzsUii5+j+WYhMsAUTyFIFt48L+Nf85rrVj69tNGDe1RVzjrGT0Pd2kcIFbZCZ00R+9wsQ4IaYoMSj/tSQU/wagpoy4VVucUaZ07ejtDfIZYVO/1E6GUH6HLlKJGyBWpY2d+hE74QQHC4B0Hxaa9w96N5sn3b4QsgM2Ihxj/9PYd61Okz2njPX6kW2fJBFLrLbrf3YOBFoJAUQj9eqx0wM6xRjb8MmtIGx0s+f0g/2QLaS7cqQAuV847NdAmB+FjcO6tiFM/a9ik3scMa90YaabcC+87pEv8Uf1UN0j/pS4zrDaaZi0qBl5GHlfaWIjNSIUsWHwaqEJ23gl9ADCmmJX2eQOcl7hzCYGRxK1NWysXs2kskGLk6NL196WcM2XWeHP6laCRS/zdMKbszbIT6vBoewG7CrF4LNjjpOf7Mzrpd7gCVe76sUAYYSmJ8djU60WsNRPjNeeMn+qlG1TFGEBZxCXaIR/ys5gOdn2qN4mhVErP/B0ZYP197n3pbITisVoyi0DoWDpu/a51STDwT9B5g/uePF3JjcYvuhIFTjCqSi8AbrFdCrYUPdfisCNqV6cJRIPx6QBVSshAwElVH9Yvqp+TWGDmuDNKb7D9N8gShQBg5/Wjf5cQHDeD5E8wmESs6Cyy04ZPprmw=
  keep-history: true
  repo: Chilipp/chilipp.github.io
  target-branch: master
  local-dir: _site
  on:
    branch: master
